/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BaseModal: typeof import('./components/BaseModal.vue')['default']
    ConfirmationModal: typeof import('./components/ConfirmationModal.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IconButtonWithTooltip: typeof import('./components/IconButtonWithTooltip.vue')['default']
    ProfileDropdown: typeof import('./components/ProfileDropdown.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
