version: "3.9"
name: l11v3spa
services:
  apache-php-8.3:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    environment:
      - APACHE_LOG_DIR=/app
      - TZ=Asia/Karachi
      - server_name=${SERVER_NAME}
      - server_port=${SERVER_PORT}
      - client_port=${CLIENT_PORT}
      - github_link=${GITHUB_LINK}
      - xdebug_port=${XDEBUG_PORT}
    ports:
      - "${SERVER_PORT}:443"
      - ${CLIENT_PORT}:${CLIENT_PORT}
    volumes:
      - ./certs:/var/www/certs
      - ../.vscode:/.vscode